### ISSUE TITLE
it outputs no class even though there is

### ISSUE THREAD

**Issue by GoogleCodeExporter** [baudm/crs-o-matic#5] opened 2015-03-13 16:48 UTC
```
What steps will reproduce the problem?
1. tried eee classes
2. tried some GE courses
3.

What is the expected output? What do you see instead?
no class

What version of the product are you using? On what operating system?


Please provide any additional information below.


```

Original issue reported on code.google.com by `nicoange...@gmail.com` on 24 Oct 2013 at 11:35

**Comment by baudm** [comment] 2019-07-14 10:19
Closing this due to lack of usable info for reproducing the bug.

**Closed by baudm** 2019-07-14 10:19 UTC
Labels: Priority-Medium, Type-Defect, auto-migrated
